export type CoverageStatus = 'not_started' | 'mapped' | 'extracting' | 'extracted' | 'reviewed';

export interface CoverageEntry {
  id: string;
  status: CoverageStatus;
  components?: Record<string, string>;
  notes?: string;
}

export interface CoverageFile {
  sections: CoverageEntry[];
}

/** A section counts toward a milestone once it has reached that stage or passed it. */
const reachedOrPast: Record<'mapped' | 'extracted' | 'reviewed', CoverageStatus[]> = {
  mapped: ['mapped', 'extracting', 'extracted', 'reviewed'],
  extracted: ['extracted', 'reviewed'],
  reviewed: ['reviewed'],
};

function percentage(count: number, total: number): string {
  if (total === 0) return '0%';
  return `${Math.round((count / total) * 100)}%`;
}

export function renderCoverageReport(coverage: CoverageFile): string {
  const sections = coverage.sections ?? [];
  const total = sections.length;

  const lines: string[] = [
    '# Coverage report',
    '',
    '<!-- Generated by `npm run report:coverage` from corpus/source-map/coverage.yaml. Do not edit by hand. -->',
    '',
    '## Summary',
    '',
    '| Milestone | Sections | Share |',
    '| --- | --- | --- |',
  ];

  for (const milestone of ['mapped', 'extracted', 'reviewed'] as const) {
    const count = sections.filter((section) =>
      reachedOrPast[milestone].includes(section.status),
    ).length;
    lines.push(`| ${milestone} | ${count} / ${total} | ${percentage(count, total)} |`);
  }

  lines.push('', `Total sections tracked: ${total}`, '');

  if (total === 0) {
    lines.push(
      'No sections are tracked yet. The structural map is built in Phase 1; until then this',
      'report is an empty skeleton rather than a claim that coverage is complete.',
      '',
    );
    return lines.join('\n');
  }

  lines.push('## Sections', '', '| Section | Status | Notes |', '| --- | --- | --- |');
  for (const section of sections) {
    lines.push(`| ${section.id} | ${section.status} | ${section.notes ?? ''} |`);
  }

  const unprocessed = sections.filter((section) => section.status === 'not_started');
  lines.push('', '## Unprocessed sections', '');
  if (unprocessed.length === 0) {
    lines.push('None.');
  } else {
    lines.push(...unprocessed.map((section) => `- ${section.id}`));
  }
  lines.push('');

  return lines.join('\n');
}
