export type CoverageStatus = 'not_started' | 'mapped' | 'extracting' | 'extracted' | 'reviewed';
export type ComponentStatus = CoverageStatus | 'not_applicable';

export interface CoverageEntry {
  id: string;
  status: CoverageStatus;
  components?: Partial<Record<ComponentName, ComponentStatus>>;
  notes?: string;
}

export interface CoverageFile {
  sections: CoverageEntry[];
}

export type SectionKind =
  | 'part'
  | 'chapter'
  | 'section'
  | 'subsection'
  | 'appendix'
  | 'table'
  | 'example'
  | 'optional_rule'
  | 'scenario_rule';

export interface SectionEntry {
  id: string;
  title: string;
  kind: SectionKind;
  parent?: string;
  redirect_to?: string;
  printed_start_page?: number | null;
  printed_end_page?: number | null;
  external_references?: string[];
}

const COMPONENTS = ['glossary', 'rules', 'tables', 'examples', 'procedures', 'entities'] as const;
type ComponentName = (typeof COMPONENTS)[number];

/** A section counts toward a milestone once it has reached that stage or passed it. */
const reachedOrPast: Record<'mapped' | 'extracted' | 'reviewed', CoverageStatus[]> = {
  mapped: ['mapped', 'extracting', 'extracted', 'reviewed'],
  extracted: ['extracted', 'reviewed'],
  reviewed: ['reviewed'],
};

const KIND_ORDER: SectionKind[] = [
  'part',
  'chapter',
  'section',
  'subsection',
  'appendix',
  'table',
  'example',
  'optional_rule',
  'scenario_rule',
];

function percentage(count: number, total: number): string {
  if (total === 0) return '0%';
  return `${Math.round((count / total) * 100)}%`;
}

function pageRange(section: SectionEntry): string {
  const { printed_start_page: start, printed_end_page: end } = section;
  if (start == null && end == null) return 'unnumbered';
  if (start == null) return `?-${end}`;
  if (end == null || end === start) return `${start}`;
  return `${start}-${end}`;
}

export function renderCoverageReport(
  coverage: CoverageFile,
  sections: SectionEntry[] = [],
): string {
  const byId = new Map(sections.map((section) => [section.id, section]));
  const entries = (coverage.sections ?? []).filter((entry) => !byId.get(entry.id)?.redirect_to);
  const redirects = sections.filter((section) => section.redirect_to !== undefined);
  const total = entries.length;

  const lines: string[] = [
    '# Coverage report',
    '',
    '<!-- Generated by `npm run report:coverage` from corpus/source-map/coverage.yaml and',
    'corpus/source-map/sections.yaml. Do not edit by hand. -->',
    '',
    '## Summary',
    '',
    '| Milestone | Sections | Share |',
    '| --- | --- | --- |',
  ];

  for (const milestone of ['mapped', 'extracted', 'reviewed'] as const) {
    const count = entries.filter((entry) => reachedOrPast[milestone].includes(entry.status)).length;
    lines.push(`| ${milestone} | ${count} / ${total} | ${percentage(count, total)} |`);
  }

  lines.push('', `Total sections tracked: ${total}`, '');
  if (redirects.length > 0) {
    lines.push(
      `${redirects.length} compatibility redirects are excluded from all extraction counts above and below.`,
      '',
      '## Compatibility redirects',
      '',
      '| Preserved ID | Canonical section |',
      '| --- | --- |',
      ...redirects.map((section) => `| ${section.id} | ${section.redirect_to} |`),
      '',
    );
  }

  if (total === 0) {
    lines.push(
      'No sections are tracked yet. The structural map is built in Phase 1; until then this',
      'report is an empty skeleton rather than a claim that coverage is complete.',
      '',
    );
    return lines.join('\n');
  }

  lines.push('## Nodes by kind', '', '| Kind | Count |', '| --- | --- |');
  const kindCounts = new Map<string, number>();
  for (const entry of entries) {
    const kind = byId.get(entry.id)?.kind ?? 'unknown';
    kindCounts.set(kind, (kindCounts.get(kind) ?? 0) + 1);
  }
  for (const kind of [...KIND_ORDER, 'unknown']) {
    const count = kindCounts.get(kind);
    if (count) lines.push(`| ${kind} | ${count} |`);
  }
  lines.push('');

  lines.push('## Unprocessed sections', '');
  const unprocessed = entries.filter((entry) => entry.status === 'not_started');
  if (unprocessed.length === 0) {
    lines.push('None. Every node in the structural map has been mapped.');
  } else {
    lines.push(...unprocessed.map((entry) => `- ${entry.id}`));
  }
  lines.push('');

  lines.push('## Component progress', '', '| Component | Extracted | Remaining | Not applicable |');
  lines.push('| --- | --- | --- | --- |');
  for (const component of COMPONENTS) {
    let extracted = 0;
    let remaining = 0;
    let notApplicable = 0;
    for (const entry of entries) {
      const status = entry.components?.[component] ?? 'not_started';
      if (status === 'not_applicable') notApplicable += 1;
      else if (status === 'extracted' || status === 'reviewed') extracted += 1;
      else remaining += 1;
    }
    lines.push(`| ${component} | ${extracted} | ${remaining} | ${notApplicable} |`);
  }
  lines.push('');

  for (const [kind, heading] of [
    ['table', 'Remaining tables'],
    ['example', 'Remaining examples'],
  ] as const) {
    const remaining = entries.filter((entry) => {
      const section = byId.get(entry.id);
      if (section?.kind !== kind) return false;
      const status = entry.components?.[kind === 'table' ? 'tables' : 'examples'] ?? 'not_started';
      return status !== 'extracted' && status !== 'reviewed' && status !== 'not_applicable';
    });
    lines.push(`## ${heading}`, '');
    if (remaining.length === 0) {
      lines.push('None.');
    } else {
      lines.push(
        `${remaining.length} of this kind still need their contents extracted.`,
        '',
        '| Node | Title | Printed pages |',
        '| --- | --- | --- |',
      );
      for (const entry of remaining) {
        const section = byId.get(entry.id);
        lines.push(
          `| ${entry.id} | ${section?.title ?? ''} | ${section ? pageRange(section) : ''} |`,
        );
      }
    }
    lines.push('');
  }

  lines.push('## Sections citing external sources', '');
  const citing = sections.filter(
    (section) => !section.redirect_to && (section.external_references ?? []).length > 0,
  );
  if (citing.length === 0) {
    lines.push('None.');
  } else {
    lines.push('| Section | External sources |', '| --- | --- |');
    for (const section of citing) {
      lines.push(`| ${section.id} | ${(section.external_references ?? []).join(', ')} |`);
    }
  }
  lines.push('');

  return lines.join('\n');
}
